name: Build/release

on: push

# on:
#   push:
#     tags:
#       - 'v*'

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Prepare for app notarization
        if: startsWith(matrix.os, 'macos')
        env:
          MACOS_CERTIFICATE: ${{ secrets.MAC_APP_CERTS }}
          MACOS_CERTIFICATE_PWD: ${{ secrets.MAC_APP_CERTS_PASSWORD }}
          KEYCHAIN_PASSWORD: cicd
        run: |
          # import code signing identity for MacOS
          echo "$MACOS_CERTIFICATE" | base64 —-decode > certificate.p12
          security create-keychain -p $KEYCHAIN_PASSWORD build.keychain security default-keychain -s build.keychain
          security unlock-keychain -p $KEYCHAIN_PASSWORD build.keychain
          security import certificate.p12 -k build.keychain -P $MACOS_CERTIFICATE_PWD -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k <your-password> build.keychain
          security find-identity
          # Import App Store Connect API key for app notarization on macOS
          security add-generic-password -a "elliot.murphy@gmail.com" -w ${{ secrets.MAC_AC_PASSWORD }} -s "AC_PASSWORD"
          mkdir -p ~/private_keys/
          echo "${{ secrets.MAC_APP_API_KEY }}" > ~/private_keys/AuthKey_${{ secrets.MAC_APP_API_KEY_ID }}.p8
      # this is tibdex/github-app-token v1.3, pinned to the commit SHA for security
      - uses: tibdex/github-app-token@36464acb844fc53b9b8b2401da68844f6b05ebb0
        id: generate-token
        with:
          app_id: ${{ secrets.AUTH_FOR_GITHUB_APP_ID }}
          private_key: ${{ secrets.AUTH_FOR_GITHUB_PRIVATE_KEY }}
      - name: Build/release Electron app
        uses: kindlyops/action-electron-forge@master
        env:
          API_KEY_ID: ${{ secrets.MAC_APP_API_KEY_ID }}
          API_KEY_ISSUER_ID: ${{ secrets.MAC_APP_API_KEY_ISSUER_ID }}
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        with:
          github_token: ${{ steps.generate-token.outputs.token }}
          mac_certs: ${{ secrets.MAC_APP_CERTS }}
          mac_certs_password: ${{ secrets.MAC_APP_CERTS_PASSWORD }}
          # TODO provision windows signing certs
          #windows_certs:
          #windows_certs_password:

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}